twig:
    debug: '%kernel.debug%'
    strict_variables: true
    form_themes:
        - 'form/layout.twig'
        - 'form/fields.twig'
    paths:
        '%kernel.project_dir%/public/theme/%bolt.theme%': ''
        '%kernel.project_dir%/vendor/bolt/bolt/templates/': 'bolt'
    default_path: '%kernel.project_dir%/vendor/bolt/bolt/templates'
    globals:
        'config': '@Bolt\Configuration\Config'
