version: '3.4'

services:
  db:
    # In production, you may want to use a managed database service
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bolt
      - MYSQL_USER=bolt
      # You should definitely change the password in production
      - MYSQL_PASSWORD=!ChangeMe!
      # You should definitely change the password in production
      - MYSQL_ROOT_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

  php:
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://bolt:!ChangeMe!@db:3306/bolt?serverVersion=5.7

volumes:
  db-data: {}
