version: '3.4'
services:
  php:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: bolt_php_dev
    env_file:
      - .env
    depends_on:
      - database
      - blackfire
    volumes:
      - ./:/var/www/bolt

  database:
    image: mariadb:10
    env_file:
      - .env
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_INITDB_SKIP_TZINFO: 0

  web:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
      target: nginx
    ports:
      - 8088:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/bolt

  node:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile 
      target: node
    volumes:
      - ./:/home/node/app

  adminer:
    image: adminer:latest
    ports:
      - 8099:80
    links:
      - database:db

  blackfire:
    image: blackfire/blackfire
    env_file:
      - .env
    ports:
      - 8707 # for blackfire probe

#  maildev:
#    image: djfarrelly/maildev
#    container_name: sf4_maildev
#    ports:
#      - 8089:80
