
# All routes, used by Bolt: Control Panel, Async and Thumbs, unless overridden
# in `../routing.yml` or another location
controllers:
    resource: '../vendor/bolt/core/src/Controller/'
    type: annotation

